version: "3.7"

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MYSQL_PASSWORD:
      external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true


services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static/
      - media-volume:/data/media/
    ports:
      - 80:80

  django_container_gunicorn:
    image: jochiwon_image:1
    networks:
      - network
    volumes:
      - static-volume:/home/jochiwon_final/staticfiles
      - media-volume:/home/jochiwon_final/media
  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - maria-database:/var/lib/mysql
    enviroment:
      MARIADB_PASSWORD: password1234
      MARIADB_ROOT_PASSWORD: django
      MYSQL_PASSWORD: django
      DJANGO_SECRET_KEY: password1234


networks:
  network:

volumes:
  static-volume:
  media-volume:
  maria-database: